<?php

function getServiceCatalog(): array
{
    return [
        'ac-service' => [
            'title' => 'AC Service',
            'card_text' => 'Installation support, troubleshooting, repair and maintenance for inverter and non-inverter AC units.',
            'page' => 'ac-service.php',
            'hero_image' => 'assets/services/service-hero-1.jpg',
            'hero_eyebrow' => 'Residential Cooling Support',
            'hero_title' => 'Dependable AC service for stable cooling, cleaner airflow and longer equipment life.',
            'hero_text' => 'We handle routine service visits, performance complaints, breakdown diagnosis and repair support for split and window AC systems with a practical, service-first approach.',
            'hero_points' => ['Installation and reinstallation', 'Cooling and gas-check diagnostics', 'Preventive maintenance support'],
            'overview_title' => 'Complete AC care for everyday comfort',
            'overview_text' => 'Our AC service work is designed to solve day-to-day cooling issues quickly while protecting long-term system performance. From weak cooling and water leakage to electrical interruptions and recurring fault conditions, we inspect the unit methodically and recommend work that is clear, practical and cost-aware.',
            'inclusions' => ['Cooling performance inspection and operating check', 'Indoor and outdoor unit cleaning support', 'Drain, fan and airflow issue diagnosis', 'Electrical connection and component fault tracing'],
            'process' => ['Initial symptom review and usage discussion', 'Visual inspection of indoor and outdoor sections', 'Testing of cooling behavior, airflow and electrical response', 'Service recommendation with repair or maintenance plan'],
            'why' => ['Suitable for inverter and non-inverter AC units', 'Focused on clean communication and practical repair decisions', 'Support for both home and small business installations'],
        ],
        'washing-machine-service' => [
            'title' => 'Washing Machine Service',
            'card_text' => 'Routine service, issue diagnosis and repair for common washing machine electrical and board problems.',
            'page' => 'washing-machine-service.php',
            'hero_image' => 'assets/services/service-hero-2.jpg',
            'hero_eyebrow' => 'Laundry Appliance Support',
            'hero_title' => 'Professional washing machine service for smoother cycles and reliable daily operation.',
            'hero_text' => 'We diagnose cycle interruptions, draining problems, spin issues and control faults with careful electrical and board-level attention where required.',
            'hero_points' => ['Top load and front load support', 'Drain, motor and control diagnostics', 'Routine service and fault correction'],
            'overview_title' => 'Practical repair support for modern washing machines',
            'overview_text' => 'Washing machine faults can interrupt household routines fast, especially when they involve drainage, spinning, panel response or PCB control issues. Our service is structured to identify the root cause, reduce repeat complaints and restore dependable operation wherever repair is technically sensible.',
            'inclusions' => ['Cycle interruption and startup issue diagnosis', 'Drain pump, inlet and outlet inspection support', 'Control panel and PCB fault tracing', 'Noise, vibration and spin-performance checks'],
            'process' => ['Review the reported symptom and machine behavior', 'Inspect the unit for electrical and mechanical faults', 'Test core functions including fill, wash, drain and spin', 'Provide a repair path with parts or board-related recommendations'],
            'why' => ['Clear service flow for household appliance repairs', 'Attention to both electrical and board-related problems', 'Focused on reliable daily usability after service'],
        ],
        'fridge-service' => [
            'title' => 'Fridge Service',
            'card_text' => 'Refrigerator cooling checks, electrical repair and PCB-related service support for reliable performance.',
            'page' => 'fridge-service.php',
            'hero_image' => 'assets/services/service-hero-3.jpg',
            'hero_eyebrow' => 'Refrigerator Care',
            'hero_title' => 'Refrigerator service support built around cooling stability and electrical reliability.',
            'hero_text' => 'We inspect common refrigerator complaints such as poor cooling, inconsistent temperature behavior, electrical faults and PCB-related issues affecting regular operation.',
            'hero_points' => ['Cooling and temperature performance checks', 'Electrical and control issue diagnosis', 'Service support for domestic refrigerator units'],
            'overview_title' => 'Service that protects cooling performance and convenience',
            'overview_text' => 'When a refrigerator starts underperforming, the issue can quickly affect food safety, energy use and everyday convenience. Our fridge service focuses on steady cooling response, clean diagnosis and practical repair support for key electrical and control-side faults.',
            'inclusions' => ['Cooling complaint and temperature-response inspection', 'Thermostat, relay and control-side fault checks', 'PCB-related diagnosis for supported models', 'Door-seal, fan and internal electrical review'],
            'process' => ['Understand the cooling complaint and symptom timing', 'Inspect unit behavior, airflow and electrical response', 'Check likely control and component failure points', 'Recommend service action to restore stable performance'],
            'why' => ['Designed for real-world household cooling complaints', 'Balanced attention to mechanical and PCB-related causes', 'Repair-first mindset where practical and economical'],
        ],
        'commercial-ac-service' => [
            'title' => 'Commercial AC',
            'card_text' => 'Service support for commercial cooling systems with attention to uptime, stable performance and practical maintenance.',
            'page' => 'commercial-ac-service.php',
            'hero_image' => 'assets/services/service-hero-4.jpg',
            'hero_eyebrow' => 'Commercial Cooling Systems',
            'hero_title' => 'Commercial AC service focused on uptime, controlled performance and efficient support response.',
            'hero_text' => 'We provide service assistance for office, retail and small commercial cooling setups where continuity, timely diagnosis and maintenance discipline matter.',
            'hero_points' => ['Performance-focused maintenance', 'Fault tracing for working commercial sites', 'Support planned around uptime needs'],
            'overview_title' => 'Cooling support for business environments',
            'overview_text' => 'Commercial AC systems need service that is disciplined, responsive and aware of operating impact. Our approach is to assess performance quickly, isolate likely causes of instability and recommend maintenance or repair actions that help maintain comfort without unnecessary disruption.',
            'inclusions' => ['System performance inspection and service checks', 'Diagnosis of recurring operational complaints', 'Maintenance support for cleaner and steadier cooling', 'Practical repair planning for business-use environments'],
            'process' => ['Review the site condition and cooling expectations', 'Inspect the operating system and visible fault indicators', 'Assess performance, airflow and control-side behavior', 'Provide a service plan aligned to uptime and practicality'],
            'why' => ['Built for small commercial and business environments', 'Focus on continuity and maintenance discipline', 'Clear communication for service decisions and next steps'],
        ],
        'inverter-ac-pcb-service' => [
            'title' => 'Inverter AC PCB Service',
            'card_text' => 'Diagnosis, repair and replacement support for inverter AC PCB issues to help restore safe and stable unit performance.',
            'page' => 'inverter-ac-pcb-service.php',
            'hero_image' => 'assets/services/service-hero-5.jpg',
            'hero_eyebrow' => 'Chip-Level Support',
            'hero_title' => 'Targeted inverter AC PCB service for control faults, unstable operation and board-level failures.',
            'hero_text' => 'This service is centered on inverter AC PCB diagnosis, fault isolation and practical repair or replacement recommendations based on the condition of the board and connected components.',
            'hero_points' => ['Board-level diagnosis support', 'Inverter control fault evaluation', 'Repair or replacement guidance'],
            'overview_title' => 'Specialized support for inverter control boards',
            'overview_text' => 'Inverter AC PCB issues can create difficult symptoms such as startup failure, irregular fan behavior, communication faults and recurring shutdown conditions. Our service focuses on identifying whether the problem originates on the board, in related sensors or through connected electrical sections before recommending the best path forward.',
            'inclusions' => ['Inspection of visible PCB damage and failure signs', 'Fault tracing related to inverter board behavior', 'Assessment of supporting components and connections', 'Guidance on repairability versus replacement'],
            'process' => ['Review the fault history and system symptoms', 'Inspect the inverter board and connected sections', 'Evaluate likely PCB, sensor or communication issues', 'Advise the most practical repair or replacement option'],
            'why' => ['Focused specifically on inverter AC board complaints', 'Useful for complex electrical and control-related faults', 'Helps reduce guesswork before replacement decisions'],
        ],
        'all-brand-ac-support' => [
            'title' => 'All Brand AC Support',
            'card_text' => 'Service available for multiple AC brands including leading residential and commercial systems, with PCB chip-level attention where needed.',
            'page' => 'all-brand-ac-support.php',
            'hero_image' => 'assets/services/service-hero-6.jpg',
            'hero_eyebrow' => 'Multi-Brand Service Coverage',
            'hero_title' => 'Flexible AC service support across major brands, models and board-related fault conditions.',
            'hero_text' => 'We support a wide range of AC brands with practical service handling for maintenance, troubleshooting and PCB-related repair needs across residential and commercial use cases.',
            'hero_points' => ['Multi-brand familiarity', 'Support across varied AC configurations', 'Board-related fault attention where needed'],
            'overview_title' => 'One service approach across multiple AC brands',
            'overview_text' => 'Brand variety should not make service more complicated for the customer. Our all-brand AC support is structured to handle different systems with a steady workflow, careful diagnosis and recommendations that reflect the actual condition of the unit rather than a one-size-fits-all response.',
            'inclusions' => ['Support for multiple leading AC brands', 'Maintenance, troubleshooting and repair assistance', 'PCB-related inspection for compatible complaints', 'Clear communication on parts, repair scope and next steps'],
            'process' => ['Confirm brand, model and complaint details', 'Inspect the unit and test core system behavior', 'Identify the likely service path based on fault condition', 'Proceed with maintenance or repair recommendations'],
            'why' => ['Useful for homes, offices and mixed-brand service needs', 'Practical support even when systems vary by model', 'Consistent service quality across multiple brand types'],
        ],
    'residential-support' => [
            'title' => 'Residential Support',
            'card_text' => 'Dependable service for AC, fridge and washing machine needs with a practical service-center approach.',
            'page' => 'residential-support.php',
            'hero_image' => 'assets/services/home-service 1.webp',
            'hero_eyebrow' => 'Home Appliance Service',
            'hero_title' => 'Dependable service for AC, fridge and washing machine needs with a practical service-center approach.',
            'hero_text' => 'We handle AC, refrigerator and washing machine service requirements for homes with a focus on practical diagnostics, clear communication and reliable repairs.',
            'hero_points' => ['AC installation, service and repair', 'Refrigerator cooling and electrical support', 'Washing machine diagnostics and repair'],
            'overview_title' => 'Complete home appliance service support',
            'overview_text' => 'Our residential support covers the main household cooling and laundry appliances with a service-center approach built on practical diagnosis, honest assessment and dependable repairs.',
            'inclusions' => ['AC installation, gas check and repair support', 'Refrigerator cooling and electrical diagnostics', 'Washing machine drain, spin and control repairs', 'Multi-brand service for household units'],
            'process' => ['Understand the complaint and appliance history', 'Inspect the unit and identify the issue', 'Provide clear repair options and recommendations', 'Execute repair with genuine parts support'],
            'why' => ['Practical approach to common appliance problems', 'Clear communication throughout the service', 'Focused on long-term reliable performance'],
        ],
        'commercial-support' => [
            'title' => 'Commercial Support',
            'card_text' => 'Commercial AC servicing focused on smooth operation, reliable response and maintenance support.',
            'page' => 'commercial-support.php',
            'hero_image' => 'assets/services/home-service-2 1.webp',
            'hero_eyebrow' => 'Commercial Cooling Service',
            'hero_title' => 'Commercial AC servicing focused on smooth operation, reliable response and maintenance support.',
            'hero_text' => 'We provide commercial AC service for offices, retail spaces and business environments with emphasis on uptime, systematic maintenance and quick response.',
            'hero_points' => ['Performance-focused maintenance', 'Business environment service support', 'Scheduled maintenance plans'],
            'overview_title' => 'Reliable commercial cooling support',
            'overview_text' => 'Our commercial support is designed for business environments where cooling continuity matters. We focus on systematic maintenance, quick fault diagnosis and planned service to minimize disruption.',
            'inclusions' => ['Commercial AC performance inspection', 'Scheduled maintenance support', 'Fault diagnosis for operational systems', 'Maintenance planning for business needs'],
            'process' => ['Assess the commercial system and usage patterns', 'Inspect performance and identify maintenance needs', 'Provide service plan with schedule options', 'Execute maintenance with minimal disruption'],
            'why' => ['Built for business environment needs', 'Focus on uptime and operational continuity', 'Flexible maintenance scheduling'],
        ],
    ];
}
